export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE'

export const GET_POST_LIST = 'GET_POST_LIST'
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
export const GET_POST_LIST_FAILURE = 'GET_POST_LIST_FAILURE'
export const RESET_GET_POST_LIST = 'RESET_GET_POST_LIST'

export const SET_REGISTER_FORM_DATA = 'SET_REGISTER_FORM_DATA'

export const POST_FAVOURITES = 'POST_FAVOURITES'
export const POST_FAVOURITES_SUCCESS = 'POST_FAVOURITES_SUCCESS'
export const POST_FAVOURITES_FAILURE = 'POST_FAVOURITES_FAILURE'
export const RESET_POST_FAVOURITES = 'RESET_POST_FAVOURITES'